In [140]:
import pandas as pd
import numpy as np
from selenium import webdriver
from pandas import DataFrame, read_csv

In [141]:
path_to_chrome_driver = '/Users/harrelblatt/summer/chromedriver'
browser = webdriver.Chrome(executable_path = path_to_chrome_driver)

In [142]:
url = 'https://www.pinnacle.com/en/odds/match/baseball/usa/mlb#height'

In [143]:
browser.get(url)

In [56]:
# Find by xml path
#browser.find_element_by_xpath("""//*[@id="sss0"]/li[19]/a""").click()

In [144]:
pitchers = browser.find_elements_by_class_name("name")
#money_lines = browser.find_elements_by_class_name("game-moneyline")
#handicaps = browser.find_elements_by_class_name("game-handicap")
#totals = browser.find_elements_by_class_name("game-total")

In [145]:
hurlers = []
for pitcher in pitchers:
    if pitcher.text != '':
        hurlers.append(pitcher.text)

# print(pitchers)
print(hurlers)



#for money_line in money_lines:
#    print(money_line.text)

#for handicap in handicaps:
#    print(handicap.text)

#a = []
#for total in totals:
#     a.append(total.text)

#print(a)

['San Francisco Giants\nT. Blach', 'Los Angeles Dodgers\nR. Hill', 'Colorado Rockies\nG MARQUEZ', 'Washington Nationals\nT ROARK', 'Atlanta Braves\nS. Newcomb', 'Philadelphia Phillies\nJ. Eickhoff', 'Cincinnati Reds\nT. Adleman', 'Miami Marlins\nA. Conley', 'Chicago Cubs\nK. Hendricks', 'Milwaukee Brewers\nJ. Guerra', 'Arizona Diamondbacks\nZ. Greinke', 'St. Louis Cardinals\nM. Leake', 'Pittsburgh Pirates\nI. Nova', 'San Diego Padres\nD. Lamet', 'Houston Astros\nC. McHugh', 'Detroit Tigers\nM. Boyd', 'Cleveland Indians\nC. Kluber', 'Chicago White Sox\nM. Gonzalez', 'Kansas City Royals\nT. Cahill', 'Boston Red Sox\nE RODRIGUEZ', 'Baltimore Orioles\nK. Gausman', 'Texas Rangers\nA. Bibens-Dirkx', 'Minnesota Twins\nA. Mejia', 'Oakland Athletics\nC. Smith', 'New York Mets\nJ. deGrom', 'Seattle Mariners\nY. Gallardo']

In [146]:
remove_carriage =[]
for word in hurlers:
    
     remove_carriage.append(word.replace('\n',' ')) 

print(remove_carriage)

['San Francisco Giants T. Blach', 'Los Angeles Dodgers R. Hill', 'Colorado Rockies G MARQUEZ', 'Washington Nationals T ROARK', 'Atlanta Braves S. Newcomb', 'Philadelphia Phillies J. Eickhoff', 'Cincinnati Reds T. Adleman', 'Miami Marlins A. Conley', 'Chicago Cubs K. Hendricks', 'Milwaukee Brewers J. Guerra', 'Arizona Diamondbacks Z. Greinke', 'St. Louis Cardinals M. Leake', 'Pittsburgh Pirates I. Nova', 'San Diego Padres D. Lamet', 'Houston Astros C. McHugh', 'Detroit Tigers M. Boyd', 'Cleveland Indians C. Kluber', 'Chicago White Sox M. Gonzalez', 'Kansas City Royals T. Cahill', 'Boston Red Sox E RODRIGUEZ', 'Baltimore Orioles K. Gausman', 'Texas Rangers A. Bibens-Dirkx', 'Minnesota Twins A. Mejia', 'Oakland Athletics C. Smith', 'New York Mets J. deGrom', 'Seattle Mariners Y. Gallardo']

In [147]:
pitcher_team_cleaned = []
for element in hurlers:
    
    element = element.replace('\n',' ')
    
    length = len(element.split())
    
    if length < 4 or length > 5:
    
        print('Format not what expected')
    
    n = length - 2
    
    groups = element.split(' ',n)
    
    team  = ' '.join(groups[:n])

    pitcher = ' '.join(groups[n:])

    pitcher_team_cleaned.append((team,pitcher))

pitcher_team_cleaned

[('San Francisco Giants', 'T. Blach'),
 ('Los Angeles Dodgers', 'R. Hill'),
 ('Colorado Rockies', 'G MARQUEZ'),
 ('Washington Nationals', 'T ROARK'),
 ('Atlanta Braves', 'S. Newcomb'),
 ('Philadelphia Phillies', 'J. Eickhoff'),
 ('Cincinnati Reds', 'T. Adleman'),
 ('Miami Marlins', 'A. Conley'),
 ('Chicago Cubs', 'K. Hendricks'),
 ('Milwaukee Brewers', 'J. Guerra'),
 ('Arizona Diamondbacks', 'Z. Greinke'),
 ('St. Louis Cardinals', 'M. Leake'),
 ('Pittsburgh Pirates', 'I. Nova'),
 ('San Diego Padres', 'D. Lamet'),
 ('Houston Astros', 'C. McHugh'),
 ('Detroit Tigers', 'M. Boyd'),
 ('Cleveland Indians', 'C. Kluber'),
 ('Chicago White Sox', 'M. Gonzalez'),
 ('Kansas City Royals', 'T. Cahill'),
 ('Boston Red Sox', 'E RODRIGUEZ'),
 ('Baltimore Orioles', 'K. Gausman'),
 ('Texas Rangers', 'A. Bibens-Dirkx'),
 ('Minnesota Twins', 'A. Mejia'),
 ('Oakland Athletics', 'C. Smith'),
 ('New York Mets', 'J. deGrom'),
 ('Seattle Mariners', 'Y. Gallardo')]

In [53]:
df = pd.DataFrame(data = pitcher_team_cleaned, columns=['Team', 'Pitcher'])
df

                     Team        Pitcher
0          Atlanta Braves     J. Teheran
1   Philadelphia Phillies  J. Hellickson
2        Colorado Rockies     G. Marquez
3    Washington Nationals       T. Roark
4         Cincinnati Reds      S. Romano
5           Miami Marlins      V. Worley
6            Chicago Cubs    J. Quintana
7       Milwaukee Brewers       B. Suter
8    Arizona Diamondbacks         R. Ray
9     St. Louis Cardinals       M. Wacha
10   San Francisco Giants       M. Moore
11    Los Angeles Dodgers        A. Wood
12         Tampa Bay Rays      A. Pruitt
13       New York Yankees      M. Tanaka
14     Kansas City Royals      J. Vargas
15         Boston Red Sox       D. Price
16         Houston Astros     D. Keuchel
17         Detroit Tigers  J. Zimmermann
18      Baltimore Orioles     C. Tillman
19          Texas Rangers     A. Cashner
20      Cleveland Indians     D. Salazar
21      Chicago White Sox     D. Holland
22        Minnesota Twins      J. Garcia
23      Oakland Athletics     D. Gossett
24          New York Mets     R. Montero
25       Seattle Mariners     A. Miranda

In [148]:
money_lines = browser.find_elements_by_class_name("game-moneyline")

money_line = []
for line in money_lines:
    if line.text != '':
        money_line.append(line.text)

money_line

df['Money Line'] = money_line

df

,Team,Pitcher,Money Line,Line,Odds,Over_Under,Total,Price
0,Atlanta Braves,J. Teheran,3.490,-1.5,2.340,Over,9.0,1.806
1,Philadelphia Phillies,J. Hellickson,1.363,1.5,1.675,Under,9.0,2.120
2,Colorado Rockies,G. Marquez,2.260,1.5,1.666,Over,9.0,1.781
3,Washington Nationals,T. Roark,1.735,-1.5,2.360,Under,9.0,2.160
4,Cincinnati Reds,S. Romano,1.952,1.5,1.549,Over,9.5,1.952
5,Miami Marlins,V. Worley,1.970,-1.5,2.639,Under,9.5,1.952
6,Chicago Cubs,J. Quintana,2.270,-1.5,2.070,Over,9.0,1.806
7,Milwaukee Brewers,B. Suter,1.724,1.5,1.847,Under,9.0,2.120
8,Arizona Diamondbacks,R. Ray,1.584,1.5,1.485,Over,8.0,1.925
9,St. Louis Cardinals,M. Wacha,2.570,-1.5,2.850,Under,8.0,1.980
10,San Francisco Giants,M. Moore,1.900,1.5,2.310,Over,8.0,1.909
11,Los Angeles Dodgers,A. Wood,2.030,-1.5,1.689,Under,8.0,2.000
12,Tampa Bay Rays,A. Pruitt,1.925,1.5,1.787,Over,9.5,1.952
13,New York Yankees,M. Tanaka,2.000,-1.5,2.150,Under,9.5,1.952
14,Kansas City Royals,J. Vargas,1.909,1.5,1.869,Over,9.5,1.884
15,Boston Red Sox,D. Price,2.020,-1.5,2.040,Under,9.5,2.020
16,Houston Astros,D. Keuchel,1.338,-1.5,1.934,Over,9.5,2.040
17,Detroit Tigers,J. Zimmermann,3.670,1.5,1.970,Under,9.5,1.869
18,Baltimore Orioles,C. Tillman,2.260,1.5,1.641,Over,11.0,1.934
19,Texas Rangers,A. Cashner,1.735,-1.5,2.410,Under,11.0,1.970
20,Cleveland Indians,D. Salazar,1.847,-1.5,1.800,Over,9.5,2.000
21,Chicago White Sox,D. Holland,2.090,1.5,2.130,Under,9.5,1.909
22,Minnesota Twins,J. Garcia,1.925,-1.5,2.429,Over,9.0,1.840
23,Oakland Athletics,D. Gossett,2.000,1.5,1.632,Under,9.0,2.080
24,New York Mets,R. Montero,1.819,1.5,1.680,Over,9.5,1.793
25,Seattle Mariners,A. Miranda,2.130,-1.5,2.330,Under,9.5,2.139

In [150]:
handicaps = browser.find_elements_by_class_name("game-handicap")


handi_caps = []
for handi in handicaps:
    if handi.text != '':
        handi_caps.append(handi.text)


        
line_odds_cleaned = []
for element in handi_caps:
    
    
    groups = element.split(' ',n)
    
    line  = ' '.join(groups[:1])

    odds = ' '.join(groups[1:])

    line_odds_cleaned.append((line,odds))



line_odds_cleaned
    
df2 = pd.DataFrame(data = line_odds_cleaned, columns=['Line', 'Odds'])

df = df.join(df2)
df

ValueError: columns overlap but no suffix specified: Index(['Line', 'Odds'], dtype='object')

In [63]:
# var1 = [(1,2),(2,4),(4,5)]

# df3 = pd.DataFrame(data = var1, columns=['x', 'y'])
# df3

# var2 = [(3,4),(4,5),(5,6)]

# df4 = pd.DataFrame(data = var2, columns=['a', 'b'])

# df5 = df3.join(df4)

# df5

   x  y  a  b
0  1  2  3  4
1  2  4  4  5
2  4  5  5  6

In [56]:
totals = browser.find_elements_by_class_name("game-total")

towtals = []
for total in totals:
    if total.text != '':
        towtals.append(total.text)
        
towtals

totals_cleaned = []
for element in towtals:
    element = element.replace('\n',' ')
    totals_cleaned.append(element)

totals_cleaned

['Over 9 1.806',
 'Under 9 2.120',
 'Over 9 1.781',
 'Under 9 2.160',
 'Over 9.5 1.952',
 'Under 9.5 1.952',
 'Over 9 1.806',
 'Under 9 2.120',
 'Over 8 1.925',
 'Under 8 1.980',
 'Over 8 1.909',
 'Under 8 2.000',
 'Over 9.5 1.952',
 'Under 9.5 1.952',
 'Over 9.5 1.884',
 'Under 9.5 2.020',
 'Over 9.5 2.040',
 'Under 9.5 1.869',
 'Over 11 1.934',
 'Under 11 1.970',
 'Over 9.5 2.000',
 'Under 9.5 1.909',
 'Over 9 1.840',
 'Under 9 2.080',
 'Over 9.5 1.793',
 'Under 9.5 2.139']

In [47]:
over_unders_cleaned = []
for element in totals_cleaned:

    groups = element.split(' ')
    
    uo  = ' '.join(groups[:1])

    num = ' '.join(groups[1:2])

    price = ' '.join(groups[2:])
    
    over_unders_cleaned.append((uo,num,price))
  
   
     
over_unders_cleaned

[('Over', '9', '1.806'),
 ('Under', '9', '2.120'),
 ('Over', '9', '1.781'),
 ('Under', '9', '2.160'),
 ('Over', '9.5', '1.952'),
 ('Under', '9.5', '1.952'),
 ('Over', '9', '1.806'),
 ('Under', '9', '2.120'),
 ('Over', '8', '1.925'),
 ('Under', '8', '1.980'),
 ('Over', '8', '1.909'),
 ('Under', '8', '2.000'),
 ('Over', '9.5', '1.952'),
 ('Under', '9.5', '1.952'),
 ('Over', '9.5', '1.884'),
 ('Under', '9.5', '2.020'),
 ('Over', '9.5', '2.040'),
 ('Under', '9.5', '1.869'),
 ('Over', '11', '1.934'),
 ('Under', '11', '1.970'),
 ('Over', '9.5', '2.000'),
 ('Under', '9.5', '1.909'),
 ('Over', '9', '1.840'),
 ('Under', '9', '2.080'),
 ('Over', '9.5', '1.793'),
 ('Under', '9.5', '2.139')]

In [66]:
df3 = pd.DataFrame(data = over_unders_cleaned, columns = ['Over_Under','Total','Price'] )


#df = df.join(df3)
df

#df._get_numeric_data()

#df.dtypes

df[['Total','Price']] = df[['Total','Price']].apply(pd.to_numeric)

df.dtypes

Team           object
Pitcher        object
Money Line     object
Line           object
Odds           object
Over_Under     object
Total         float64
Price         float64
dtype: object

In [69]:
df[['Money Line','Line','Odds']] = df[['Money Line','Line','Odds']].apply(pd.to_numeric)


df
df.dtypes

Team           object
Pitcher        object
Money Line    float64
Line          float64
Odds          float64
Over_Under     object
Total         float64
Price         float64
dtype: object

In [70]:
df

,Team,Pitcher,Money Line,Line,Odds,Over_Under,Total,Price
0,Atlanta Braves,J. Teheran,1.847,-1.5,2.340,Over,9.0,1.806
1,Philadelphia Phillies,J. Hellickson,2.090,1.5,1.675,Under,9.0,2.120
2,Colorado Rockies,G. Marquez,2.360,1.5,1.666,Over,9.0,1.781
3,Washington Nationals,T. Roark,1.675,-1.5,2.360,Under,9.0,2.160
4,Cincinnati Reds,S. Romano,2.130,1.5,1.549,Over,9.5,1.952
5,Miami Marlins,V. Worley,1.819,-1.5,2.639,Under,9.5,1.952
6,Chicago Cubs,J. Quintana,1.657,-1.5,2.070,Over,9.0,1.806
7,Milwaukee Brewers,B. Suter,2.400,1.5,1.847,Under,9.0,2.120
8,Arizona Diamondbacks,R. Ray,2.050,1.5,1.485,Over,8.0,1.925
9,St. Louis Cardinals,M. Wacha,1.877,-1.5,2.850,Under,8.0,1.980
10,San Francisco Giants,M. Moore,3.710,1.5,2.310,Over,8.0,1.909
11,Los Angeles Dodgers,A. Wood,1.333,-1.5,1.689,Under,8.0,2.000
12,Tampa Bay Rays,A. Pruitt,2.520,1.5,1.787,Over,9.5,1.952
13,New York Yankees,M. Tanaka,1.606,-1.5,2.150,Under,9.5,1.952
14,Kansas City Royals,J. Vargas,2.610,1.5,1.869,Over,9.5,1.884
15,Boston Red Sox,D. Price,1.571,-1.5,2.040,Under,9.5,2.020
16,Houston Astros,D. Keuchel,1.581,-1.5,1.934,Over,9.5,2.040
17,Detroit Tigers,J. Zimmermann,2.580,1.5,1.970,Under,9.5,1.869
18,Baltimore Orioles,C. Tillman,2.179,1.5,1.641,Over,11.0,1.934
19,Texas Rangers,A. Cashner,1.781,-1.5,2.410,Under,11.0,1.970
20,Cleveland Indians,D. Salazar,1.456,-1.5,1.800,Over,9.5,2.000
21,Chicago White Sox,D. Holland,3.000,1.5,2.130,Under,9.5,1.909
22,Minnesota Twins,J. Garcia,1.925,-1.5,2.429,Over,9.0,1.840
23,Oakland Athletics,D. Gossett,2.000,1.5,1.632,Under,9.0,2.080
24,New York Mets,R. Montero,2.360,1.5,1.680,Over,9.5,1.793
25,Seattle Mariners,A. Miranda,1.680,-1.5,2.330,Under,9.5,2.139

In [131]:
#df.Team = df.Team.astype(str)

a = df.loc[0:10,'Odds']

for odd in a:
    print(a)

#a = df.loc[:,'Odds']
#print(a)

#for line in a:
#    print(line**2)


#df
#df.dtypes

0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64
0     2.340
1     1.675
2     1.666
3     2.360
4     1.549
5     2.639
6     2.070
7     1.847
8     1.485
9     2.850
10    2.310
Name: Odds, dtype: float64

In [117]:
class PartyAnimal:
    x = 0
    def party(self):
        
        self.x = self.x + 1
        print('Sof far',self.x)
       

an = PartyAnimal()

an.party()
#an.party()
#an.party()

#dir(PartyAnimal)

Sof far 1

In [107]:
#dir(an)

#q = "ssd"
#dir(q)